"""empty message

Revision ID: a4a1a1ebb875
Revises: 
Create Date: 2022-01-27 14:18:46.847248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a1a1ebb875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha_hash', sa.String(length=70), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('valor_minimo_do_pedido', sa.Integer(), nullable=True),
    sa.Column('valor_maximo', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingrediente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=70), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('preco', sa.Float(precision=15), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente_cupom',
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], )
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.Float(precision=15), nullable=False),
    sa.Column('valor_pos_desconto', sa.Float(precision=15), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_produto',
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_produto')
    op.drop_table('pedido')
    op.drop_table('cliente_cupom')
    op.drop_table('produto')
    op.drop_table('ingrediente')
    op.drop_table('funcionario')
    op.drop_table('cupom')
    op.drop_table('cliente')
    # ### end Alembic commands ###
